### ISSUE TITLE
Error with OkHttpUploader/MediaType on sync

### ISSUE THREAD

**Issue by DavidSerr** [DataDog/dd-sdk-android-gradle-plugin#28]
**Describe what happened**
Following your instructions I added the plugin like this:

```groovy
// In your project's build.gradle script
buildscript {
    dependencies {
        classpath("com.datadoghq:dd-sdk-android-gradle-plugin:1.0.0")
    }
}

// In your app's build.gradle script
plugins {
    id("dd-sdk-android-gradle-plugin")
}

// or 
apply plugin: "dd-sdk-android-gradle-plugin"
```
after 'Sync Project with Gradle Files' I get the following error:

```
Caused by: java.lang.NoClassDefFoundError: okhttp3/MediaType
	at com.datadog.gradle.plugin.internal.OkHttpUploader.<clinit>(OkHttpUploader.kt:124)
	at com.datadog.gradle.plugin.DdMappingFileUploadTask.<init>(DdMappingFileUploadTask.kt:34)
	at com.datadog.gradle.plugin.DdMappingFileUploadTask_Decorated.<init>(Unknown Source)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1969)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:468)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:50)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:90)
	... 158 more
Caused by: java.lang.ClassNotFoundException: okhttp3.MediaType
	... 166 more
```
or sometimes I get another one probable related with the same class, always with the same result,
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.datadog.gradle.plugin.internal.OkHttpUploader
	at com.datadog.gradle.plugin.DdMappingFileUploadTask.<init>(DdMappingFileUploadTask.kt:34)
	at com.datadog.gradle.plugin.DdMappingFileUploadTask_Decorated.<init>(Unknown Source)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1969)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:468)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:50)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:90)
	... 158 more
```
I think is related with a possible conflict regarding okhttp library version as I saw you are using version "3.12.6", I'm using the last version "4.9.1", I tried to force the version on a modular Android project but the error is still there.

**Steps to reproduce the issue:**
Try to add the plugin on Android modular project with several dependencies and the sync fails.

**Describe what you expected:**
A correct gradle sync after plugin added.

**Additional context**
 - Android Build Tools version: 30.0.3
 - Gradle version: 4.1.3
 - OS version: min_sdk_version -> 23, target_sdk_version -> 30
 - Plugin version: 1.0.0
 - Proguard configuration: tested on debug (not needed)

**Comment by 0xnm** [comment]
Hello @DavidSerr ! Indeed there is an issue with version `1.0.0`, can you please try version `1.0.1` and let us know if it works for you?

**Comment by DavidSerr** [comment]
Yeah, with the new update now is working, Thanks!

**Comment by 0xnm** [comment]
great to know!
