### ISSUE TITLE
[CIRCULAR REFERENCE:com.android.tools.r8.errors.a] Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by chithraboopalan271** [DataDog/dd-sdk-android-gradle-plugin#80]
Dear Team,

I have included Datadog plugin and the depedency as below in my app build.gradle file,

plugins {
    id("com.datadoghq.dd-sdk-android-gradle-plugin") version "1.3.0"
}

 implementation "com.datadoghq:dd-sdk-android:1.11.1"

I am building with minifyenabled true. But the build is getting failed with the below error,
[CIRCULAR REFERENCE:com.android.tools.r8.errors.a] Caused by: java.lang.NullPointerException

> com.android.tools.r8.CompilationFailedException: Compilation failed to complete

Can you please help me on how to resolve this issue ?

Thanks in advance

**Comment by xgouchet** [comment]
Hi @chithraboopalan271 , can you provide us with your full gradle build files, and also share the full stacktrace? The exception you mention is happening in the R8 compiler, but your message doesn't provide enough information regarding the root cause of your issue.

**Comment by chithraboopalan271** [comment]
@xgouchet Thanks for the reply. 

The build is executing fine before adding the datadog dependency, all I did was including the below dependency in my app build.gradle,

implementation "com.datadoghq:dd-sdk-android:1.11.1"

After adding the dependency,  I get the build error as below, 


 R8: com.android.tools.r8.errors.a
	at com.android.tools.r8.ir.conversion.O.b(:57)
	at com.android.tools.r8.ir.conversion.O.a(:390)
	at com.android.tools.r8.ir.conversion.O.a(:336)
	at com.android.tools.r8.utils.U0.a(:10)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: java.util.concurrent.ExecutionException: com.android.tools.r8.errors.a
		at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
		at com.android.tools.r8.utils.U0.a(:14)
		at com.android.tools.r8.utils.U0.a(:9)
		at com.android.tools.r8.ir.conversion.a0.a(:49)
		at com.android.tools.r8.ir.conversion.O.a(:160)
		at com.android.tools.r8.R8.a(:354)
		at com.android.tools.r8.R8.c(:1)
		at com.android.tools.r8.R8.b(:1)
		at com.android.tools.r8.utils.W.a(:30)
		at com.android.tools.r8.R8.a(:28)
		at com.android.tools.r8.R8.run(:3)
		at com.android.builder.dexing.R8Tool.runR8(r8Tool.kt:247)
		at com.android.build.gradle.internal.tasks.R8Task$Companion.shrink(R8Task.kt:472)
		at com.android.build.gradle.internal.tasks.R8Task.doTaskAction(R8Task.kt:334)
		at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:74)
		at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:34)
		at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:91)
		at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:57)
		at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
		at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
		at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
		at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:555)
		at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
		at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
		at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
		at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
		at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
		at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
		at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
		at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
		at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
		at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:540)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:523)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:108)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:271)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:260)
		at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:34)
		at java.util.Optional.orElseGet(Optional.java:267)
		at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:34)
		at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
		at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
		at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
		at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
		at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
		at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
		at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
		at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
		at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
		at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
		at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
		at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:42)
		at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
		at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
		at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
		at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
		at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
		at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
		at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
		at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
		at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
		at java.util.Optional.map(Optional.java:215)
		at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
		at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
		at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
		at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
		at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
		at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
		at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
		at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
		at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
		at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
		at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
		at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
		at java.util.Optional.orElseGet(Optional.java:267)
		at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
		at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
		at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
		at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
		at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
		at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:187)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:179)
		at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
		at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
		at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
		at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
		at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
		at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
		at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
		at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
		at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
		at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
		at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
		at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
		at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
		at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
		at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
		at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
		at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
		at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
		at java.lang.Thread.run(Thread.java:748)
	[CIRCULAR REFERENCE:com.android.tools.r8.errors.a]
Caused by: java.lang.NullPointerException
	at com.android.tools.r8.ir.optimize.g0.a(:52)
	at com.android.tools.r8.ir.conversion.O.a(:486)
	at com.android.tools.r8.ir.conversion.O.a(:417)
	at com.android.tools.r8.ir.conversion.O.b(:53)
	... 8 more

**Note** 

I am using DashO obfuscation.

Here is my build.gradle where the dependency is added,

apply plugin: 'com.android.library'
apply from: '../jacoco-mcs.gradle'
apply from: '../sonar-mcs.gradle'
apply from: 'dasho.gradle'

android {
    compileSdkVersion 30
    buildToolsVersion '30.0.3'
    compileOptions.encoding = 'ISO-8859-1'
    useLibrary 'org.apache.http.legacy'
    android.defaultConfig.vectorDrawables.useSupportLibrary = true
    defaultConfig {
        versionCode 1
        versionName "1.0.0"
        minSdkVersion 23
        targetSdkVersion 30
        multiDexEnabled true
        ndk {
            abiFilters  "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    android {
        lintOptions {
            abortOnError false
        }

        packagingOptions {
            exclude 'META-INF/DEPENDENCIES'
            exclude 'META-INF/proguard/coroutines.pro'
            pickFirst 'lib/x86_64/libsqlcipher.so'
            pickFirst 'lib/armeabi/libsqlcipher.so'
            pickFirst 'lib/x86/libsqlcipher.so'
            pickFirst 'lib/armeabi-v7a/libsqlcipher.so'
            pickFirst 'lib/arm64-v8a/libsqlcipher.so'
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    flavorDimensions "mode"
    productFlavors {
        flavour1 {
            dimension "mode"
        }
        flavour2 {
            dimension "mode"
        }
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
            unitTests.returnDefaultValues = true
        }
    }

}

configurations.all {
    // check for updates every build
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

dependencies {
    implementation 'androidx.lifecycle:lifecycle-process:2.2.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.2'
    implementation 'com.google.android.material:material:1.2.1'
    implementation "net.zetetic:android-database-sqlcipher:4.4.0@aar"
    implementation "androidx.sqlite:sqlite:2.0.1"
    implementation "androidx.browser:browser:1.2.0"


    //firebase
    implementation ('com.google.firebase:firebase-core:17.5.0'){
        exclude group: 'com.google.android.gms', module: 'play-services-ads-identifier'
    }
    implementation 'com.google.firebase:firebase-iid:17.0.4'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'

    //google play dependencies
    implementation 'com.google.android.gms:play-services-base:16.0.1'
    implementation 'com.google.android.gms:play-services-maps:16.0.0'
    implementation 'com.google.android.gms:play-services-location:16.0.0'
    implementation 'com.google.android.gms:play-services-safetynet:16.0.0'
    implementation 'com.google.maps.android:android-maps-utils:0.5+'
    implementation 'com.wdullaer:materialdatetimepicker:2.3.0'
    implementation 'com.google.code.gson:gson:2.2.4'
    implementation 'org.apache.commons:commons-text:1.9'
    implementation 'com.android.volley:volley:1.1.0'
    implementation 'com.googlecode.json-simple:json-simple:1.1'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'es.voghdev.pdfviewpager:library:1.1.3'

    implementation 'com.google.android.gms:play-services-auth:17.0.0'
    implementation 'com.google.android.gms:play-services-auth-api-phone:17.4.0'

    implementation ('androidx.legacy:legacy-support-v13:1.0.0'){
        exclude group: 'com.android.support', module: 'support-annotations,support-v4'
    }

    implementation(
            [group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.10.0'],
            [group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.10.0'],
            [group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.10.0']
    )

    implementation "androidx.viewpager2:viewpager2:1.0.0"

    //Test dependencies
    implementation 'commons-codec:commons-codec:1.15'
    androidTestImplementation 'junit:junit:4.13.1'
    androidTestImplementation 'junit:junit:4.13.1'
    androidTestImplementation 'androidx.multidex:multidex-instrumentation:2.0.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
 
    androidTestImplementation 'com.squareup.spoon:spoon-client:1.7.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test:rules:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-web:3.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.3.0'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.2.0'

    testImplementation 'junit:junit:4.13.1'
    androidTestImplementation 'junit:junit:4.13.1'
    testImplementation 'org.robolectric:robolectric:4.4'
    testImplementation "org.robolectric:shadows-multidex:4.4"
    testImplementation 'org.hamcrest:hamcrest-library:1.3'
    testImplementation 'org.robolectric:shadows-framework:4.4'
    testImplementation 'org.mockito:mockito-core:2.23.0'
    testImplementation 'androidx.test:core:1.3.0'
    debugImplementation('androidx.fragment:fragment-testing:1.2.5') {
        exclude group: 'androidx.test', module: 'monitor'
    }

    testImplementation 'org.powermock:powermock-api-mockito2:2.0.0'
    testImplementation 'org.powermock:powermock-module-junit4-rule-agent:1.7.4'
    testImplementation 'org.powermock:powermock-module-junit4-rule:1.7.4'
    testImplementation 'org.powermock:powermock-module-junit4:1.7.4'

    //Datadog rum monitoring
    implementation "com.datadoghq:dd-sdk-android:1.11.1”
}

**Comment by xgouchet** [comment]
Thanks for providing us with your gradle build file. I tried reproducing your issue, but couldn't get the same error that you have. Note that because I don't have your `dasho.gradle` file here, I must be missing some configuration too. Did you try disabling the `dasho` plugin, to see if you have the same issue?

**Comment by chithraboopalan271** [comment]
Yes it builds fine with disabling dasho. looks like some configuration needs to be added.

Meanwhile I have found the similar issue here, https://issuetracker.google.com/issues/162568140 . Let me check further. Thanks @xgouchet

**Comment by chithraboopalan271** [comment]
Yes it builds fine with disabling dasho. looks like some configuration needs to be added with the obfusction tool used.
